# Generated by Django 3.0.8 on 2020-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ninguno', max_length=251)),
                ('title_color', models.CharField(default='#ffffff', max_length=251)),
                ('title_2', models.CharField(default='ninguno', max_length=251)),
                ('title_color_2', models.CharField(default='#ffffff', max_length=251)),
                ('title_3', models.CharField(default='ninguno', max_length=251)),
                ('title_color_3', models.CharField(default='#ffffff', max_length=251)),
                ('subtitle', models.CharField(default=False, max_length=251)),
                ('subtitle_color', models.CharField(default='#ffffff', max_length=251)),
                ('subtitle_2', models.CharField(default=False, max_length=251)),
                ('subtitle_color_2', models.CharField(default='#ffffff', max_length=251)),
                ('subtitle_3', models.CharField(default=False, max_length=251)),
                ('subtitle_color_3', models.CharField(default='#ffffff', max_length=251)),
                ('banner', models.ImageField(upload_to='banner')),
                ('banner_2', models.ImageField(default=False, upload_to='banner')),
                ('banner_3', models.ImageField(default=False, upload_to='banner')),
                ('status', models.BooleanField(default=False)),
                ('status_2', models.BooleanField(default=False)),
                ('status_3', models.BooleanField(default=False)),
                ('login_image', models.ImageField(default=False, upload_to='login_image')),
            ],
        ),
    ]
