# Generated by Django 3.0.8 on 2020-09-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ninguno', max_length=251)),
                ('title_color', models.CharField(default='#ffffff', max_length=251)),
                ('title_2', models.CharField(default='ninguno', max_length=251)),
                ('title_color_2', models.CharField(default='#ffffff', max_length=251)),
                ('title_3', models.CharField(default='ninguno', max_length=251)),
                ('title_color_3', models.CharField(default='#ffffff', max_length=251)),
                ('subtitle', models.CharField(default=False, max_length=251)),
                ('subtitle_color', models.CharField(default='#ffffff', max_length=251)),
                ('subtitle_2', models.CharField(default=False, max_length=251)),
                ('subtitle_color_2', models.CharField(default='#ffffff', max_length=251)),
                ('subtitle_3', models.CharField(default=False, max_length=251)),
                ('subtitle_color_3', models.CharField(default='#ffffff', max_length=251)),
                ('status', models.BooleanField(default=False)),
                ('status_2', models.BooleanField(default=False)),
                ('status_3', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen1', to='images.Images')),
                ('banner_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen2', to='images.Images')),
                ('banner_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen3', to='images.Images')),
                ('login_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen4', to='images.Images')),
            ],
        ),
    ]
