# Generated by Django 3.0.8 on 2020-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner1',
            name='banner',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='banner1',
            name='banner_2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='banner1',
            name='banner_3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='banner1',
            name='login_image',
            field=models.URLField(default=False),
        ),
    ]
