# Generated by Django 3.0.8 on 2020-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FIAT', 'FIAT'), ('FORD', 'FORD')], default='Otros', max_length=250)),
                ('exact_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('link', models.CharField(max_length=291)),
                ('principal_image', models.ImageField(upload_to='products')),
                ('banner_image1', models.ImageField(upload_to='products')),
                ('banner_image2', models.ImageField(blank=True, upload_to='products')),
                ('banner_image3', models.ImageField(blank=True, upload_to='products')),
                ('offer', models.BooleanField(default=False)),
                ('new_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
