# Generated by Django 3.0.8 on 2020-09-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=251)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('exact_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
                ('link', models.CharField(max_length=291)),
                ('offer', models.BooleanField(default=False)),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('banner_images', models.ManyToManyField(related_name='fotitos', to='images.Images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('principal_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotito', to='images.Images')),
            ],
        ),
    ]
