# Generated by Django 3.0.8 on 2020-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner_image1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_image2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_image3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='principal_image',
            field=models.URLField(),
        ),
    ]
